version: '2'

services:

  ##############################
  #    Setup server container
  ##############################

  server:
    build: ./server
    expose:
      - 8000
    environment:
      API_HOST: http://localhost
      APP_SERVER_PORT: 8000
    ports:
      - 8000:8000
    volumes:
      - ./server:/srv/app/admin-serve

  ##############################
  #    Setup client container
  ##############################

  client:
    build: ./client
    environment:
      PORT: 4000
    expose:
      - 4000
    ports:
      - 4000:4000
    volumes:
      - ./client/src:/srv/app/admin-client/src
      - ./client/public:/srv/app/admin-client/public
    links:
      - server
