version: '3'

##############################
#    Setup server container
##############################

services:
  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server:/srv/app/admin-server

##############################
#    Setup client container
##############################

  client:
    build: ./client
    environment:
      PORT: ${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/srv/app/admin-client/src
      - ./client/public:/srv/app/admin-client/public
    links:
      - server
